# Generated by Django 6.0.5 on 2026-05-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=20, unique=True)),
                ('menu_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Serology', 'Serology'), ('Haematology', 'Haematology'), ('Biochemistry', 'Biochemistry'), ('Microbiology', 'Microbiology'), ('Immunology', 'Immunology'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['menu_code'],
            },
        ),
        migrations.CreateModel(
            name='AssayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_code', models.CharField(max_length=20, unique=True)),
                ('assay_name', models.CharField(max_length=150)),
                ('sample_type', models.CharField(max_length=50)),
                ('tat_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assays', to='labtests.testmenumaster')),
            ],
            options={
                'ordering': ['assay_code'],
            },
        ),
    ]
